<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="SmokeSuite" duration-ms="34396" started-at="2019-07-30T06:23:17Z" finished-at="2019-07-30T06:23:51Z">
    <groups>
    </groups>
    <test name="LoginTestCase" duration-ms="34396" started-at="2019-07-30T06:23:17Z" finished-at="2019-07-30T06:23:51Z">
      <class name="com.diyotta.tests.LoginTest">
        <test-method status="FAIL" signature="closeBrowser()[pri:0, instance:com.diyotta.tests.LoginTest@ae45eb6]" name="closeBrowser" duration-ms="55" started-at="2019-07-30T06:23:17Z" finished-at="2019-07-30T06:23:17Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.diyotta.drivers.DriverCreation.destroyDriver(DriverCreation.java:40)
at com.diyotta.tests.CommonTestMethods.closeBrowser(CommonTestMethods.java:24)
at com.diyotta.tests.LoginTest.closeBrowser(LoginTest.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.diyotta.tests.LoginTest@ae45eb6]" name="login" duration-ms="34173" started-at="2019-07-30T06:23:17Z" finished-at="2019-07-30T06:23:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- com.diyotta.tests.LoginTest -->
    </test> <!-- LoginTestCase -->
  </suite> <!-- SmokeSuite -->
</testng-results>
